#!/usr/bin/env bash
# install.sh — wire the Assert.IQ agent pack into a repo for dual-target use.
# Idempotent: safe to re-run.
#
# What it does:
#   1. Renders .assert-iq/dreaming/session-events.json from its template and
#      syncs it into .claude/settings.json (hooks key — the harness contract),
#      preserving any other keys you already have in .claude/settings.json.
#   2. Scaffolds the Dreaming memory store at .assert-iq/memory/.
#   3. Creates .claude/skills as a symlink to ../.github/skills so Claude
#      Code discovers the same skills Copilot does. Falls back to copy on
#      filesystems that don't support symlinks.
#   4. Wires Kiro: renders .kiro/hooks/assert-iq-dreaming.json from its
#      template and links .kiro/skills the same way as .claude/skills.
#      Kiro's steering and agents are committed pack source (generated by
#      scripts/sync-kiro.sh at authoring time), so they need no install step.
#
# Copilot needs no extra wiring — it reads .github/* natively.
#
# Uninstall: pass --uninstall (or -u) to reverse the above. The uninstall
# step only removes pack-owned wiring; your other keys in
# .claude/settings.json and your .assert-iq/memory/ store are preserved.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Defense-in-depth: refuse to operate at filesystem root if ROOT ever
# resolves to something dangerous (e.g., script relocated to "/").
[[ -n "$ROOT" && "$ROOT" != "/" ]] || { printf 'install.sh: refusing to operate at filesystem root (ROOT=%q)\n' "$ROOT" >&2; exit 1; }

HOOKS_TEMPLATE_LEGACY="$ROOT/hooks/hooks.json"
EVENTS_TEMPLATE="$ROOT/.assert-iq/dreaming/session-events.template.json"
CLAUDE_HOOKS_TEMPLATE="$ROOT/.assert-iq/dreaming/claude-hooks.posix.template.json"
EVENTS_SRC="$ROOT/.assert-iq/dreaming/session-events.json"
CLAUDE_HOOKS_SRC="$ROOT/.assert-iq/dreaming/.claude-hooks.rendered.json"
MEMORY_DIR="$ROOT/.assert-iq/memory"
SETTINGS_DST="$ROOT/.claude/settings.json"
SKILLS_SRC_REL="../.github/skills"
SKILLS_DST="$ROOT/.claude/skills"
RENDER_LIB="$ROOT/.assert-iq/dreaming/scripts/lib/render-events.sh"

# Kiro (third harness). Unlike Claude, Kiro's hooks are a STANDALONE file in
# .kiro/hooks/ rather than a key inside a shared settings file, so there is no
# merge step and no risk of clobbering unrelated user config -- the file is
# ours outright. Skills use the same symlink trick as .claude/skills.
KIRO_HOOKS_TEMPLATE="$ROOT/.assert-iq/dreaming/kiro-hooks.posix.template.json"
KIRO_HOOKS_DST="$ROOT/.kiro/hooks/assert-iq-dreaming.json"
KIRO_SKILLS_DST="$ROOT/.kiro/skills"

say() { printf '%s\n' "$*"; }
fail() { printf 'install.sh: %s\n' "$*" >&2; exit 1; }

# Accept --yes/-y in any position as a no-op (parity with bootstrap.sh; this
# installer has no interactive prompts, so the flag is informational only).
args=()
for a in "$@"; do
  case "$a" in --yes|-y) ;; *) args+=("$a") ;; esac
done
set -- "${args[@]:-}"

# ---- Uninstall path ------------------------------------------------------
case "${1:-}" in
  --uninstall|-u)
    say "=== Assert.IQ install.sh: uninstall ==="
    # 1. Remove .claude/skills (symlink or copied dir).
    if [[ -L "$SKILLS_DST" || -e "$SKILLS_DST" ]]; then
      rm -rf "$SKILLS_DST"
      say "[ok] removed $SKILLS_DST"
    fi
    # 2. Strip hooks key from .claude/settings.json (preserve other keys).
    if [[ -f "$SETTINGS_DST" ]]; then
      if command -v jq >/dev/null 2>&1; then
        tmp="$(mktemp "$SETTINGS_DST.XXXXXX")"
        if jq 'del(.hooks)' "$SETTINGS_DST" > "$tmp" 2>/dev/null && [[ -s "$tmp" ]]; then
          # If only "{}" remains (no other keys), drop the file entirely.
          if [[ "$(jq -r 'keys | length' "$tmp")" == "0" ]]; then
            rm -f "$SETTINGS_DST" "$tmp"
            say "[ok] removed $SETTINGS_DST (was hooks-only)"
          else
            mv "$tmp" "$SETTINGS_DST"
            say "[ok] stripped hooks key from $SETTINGS_DST"
          fi
        else
          rm -f "$tmp"
          say "[skip] could not parse $SETTINGS_DST; left untouched"
        fi
      else
        say "[skip] jq not installed; cannot safely strip hooks key from $SETTINGS_DST"
      fi
    fi
    # 3. Remove rendered session-events.json (committed source is the template).
    if [[ -f "$EVENTS_SRC" ]]; then
      rm -f "$EVENTS_SRC"
      say "[ok] removed $EVENTS_SRC"
    fi
    if [[ -f "$CLAUDE_HOOKS_SRC" ]]; then
      rm -f "$CLAUDE_HOOKS_SRC"
      say "[ok] removed $CLAUDE_HOOKS_SRC"
    fi
    # 3a. Remove any leftover rendered file from the retired hooks feature.
    if [[ -f "$HOOKS_TEMPLATE_LEGACY" ]]; then
      rm -f "$HOOKS_TEMPLATE_LEGACY"
      say "[ok] removed legacy $HOOKS_TEMPLATE_LEGACY"
    fi
    # 4. Remove Kiro-generated wiring. Steering, agents and settings/mcp.json
    #    are committed pack SOURCE, not install output, so they stay -- same
    #    reason .github/ stays.
    if [[ -L "$KIRO_SKILLS_DST" || -e "$KIRO_SKILLS_DST" ]]; then
      rm -rf "$KIRO_SKILLS_DST"
      say "[ok] removed $KIRO_SKILLS_DST"
    fi
    if [[ -f "$KIRO_HOOKS_DST" ]]; then
      rm -f "$KIRO_HOOKS_DST"
      say "[ok] removed $KIRO_HOOKS_DST"
    fi
    if [[ -d "$ROOT/.kiro/hooks" ]] && [[ -z "$(ls -A "$ROOT/.kiro/hooks")" ]]; then
      rmdir "$ROOT/.kiro/hooks"
      say "[ok] removed empty .kiro/hooks/"
    fi

    # 5. Remove .claude dir if now empty.
    if [[ -d "$ROOT/.claude" ]] && [[ -z "$(ls -A "$ROOT/.claude")" ]]; then
      rmdir "$ROOT/.claude"
      say "[ok] removed empty .claude/"
    fi
    say ""
    say "Uninstall complete."
    say "Pack source files (.github/, .kiro/steering, .kiro/agents, CLAUDE.md,"
    say "AGENTS.md, etc.) are unchanged."
    say "Your .assert-iq/memory/ store is preserved."
    exit 0
    ;;
  --help|-h)
    sed -n '2,18p' "${BASH_SOURCE[0]}"
    exit 0
    ;;
esac

# ---- Windows: this installer produces Windows-BROKEN artifacts --------------
# Not a speed complaint like bootstrap.sh -- the OUTPUT is wrong for Windows:
#
#   1. .claude/settings.json is rendered from claude-hooks.posix.template.json,
#      so it declares shell="bash" and points at the .sh hook scripts. The
#      Windows-native template (powershell + .ps1 scripts) is what Claude Code
#      needs here.
#   2. __PACK_ROOT__ is substituted with the MSYS path ("/c/Users/..."), which
#      is meaningless to PowerShell. The Copilot session-events `windows`
#      override then does `Test-Path '/c/Users/...'` -> false -> `exit 0`, so
#      the Dreaming hooks silently no-op under VS Code on Windows. Verified.
#
# install.ps1 renders both correctly. Refuse and say so; --allow-msys (or
# AIQ_ALLOW_MSYS=1, which the bash test suites set because they deliberately
# exercise the POSIX path) overrides.
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*)
    if [[ "${AIQ_ALLOW_MSYS:-0}" != "1" ]] && [[ " $* " != *" --allow-msys "* ]]; then
      cat >&2 <<'MSYSEOF'
ERROR: you are running the bash installer on Windows (Git Bash/MSYS).

  It would write a Windows-broken config: .claude/settings.json would declare
  shell="bash" with POSIX hook scripts, and the baked pack root would be an
  MSYS path ("/c/Users/...") that PowerShell cannot resolve -- so the Dreaming
  hooks would silently do nothing under both Claude Code and VS Code.

  Use the PowerShell installer instead:

      pwsh -File install.ps1

  PowerShell 7+ is recommended. Windows PowerShell 5.1 is supported too --
  swap 'pwsh' for 'powershell' in the commands above.
  Check your environment first with:

      pwsh -File scripts/check-environment.ps1

  WSL is NOT affected -- inside WSL this is Linux and bash is the right path.
  To override anyway: re-run with --allow-msys (or set AIQ_ALLOW_MSYS=1).
MSYSEOF
      exit 2
    fi
    ;;
esac

[[ -f "$EVENTS_TEMPLATE" ]] || fail "missing $EVENTS_TEMPLATE"
[[ -f "$RENDER_LIB" ]] || fail "missing $RENDER_LIB"

# shellcheck source=.assert-iq/dreaming/scripts/lib/render-events.sh
source "$RENDER_LIB"

mkdir -p "$ROOT/.claude/agents"

# ---- 0. scaffold the Dreaming memory store -------------------------------
mkdir -p "$MEMORY_DIR/topics" "$MEMORY_DIR/logs" "$MEMORY_DIR/.dream"

# Verdict archive (v1.7.0+) and pre-dream memory snapshots. Both are
# git-ignored runtime sinks, so a fresh clone has neither; without them the
# first /risk-assess-pr or /dream has nowhere to write.
mkdir -p "$ROOT/.assert-iq/verdicts/archive" "$ROOT/.assert-iq/dreaming/.snapshots" \
         "$ROOT/.assert-iq/business-metrics/reports"
[[ -f "$MEMORY_DIR/.dream/state.json" ]] || \
  printf '{\n  "last_dream_utc": null,\n  "sessions_since_dream": 0\n}\n' > "$MEMORY_DIR/.dream/state.json"
# MEMORY.md is git-ignored (never ship maintainer memory); seed a clean index
# if this clone doesn't have one yet.
[[ -f "$MEMORY_DIR/MEMORY.md" ]] || cat > "$MEMORY_DIR/MEMORY.md" <<'MEOF'
# MEMORY.md — Project Memory Index

_Last consolidated: never — run `/dream` to populate_

<!--
Long-term memory INDEX for the Assert.IQ Dreaming feature (loaded at session
start, index only). Maintained by the /dream consolidation pass:
  - Hard cap: 200 lines; one-line pointers into topics/.
  - Absolute dates only. Facts/decisions/preferences, not transcript excerpts.
Hand-edit freely; the instruction files under .github/instructions/ are the
immutable rules tier and are never modified by dreaming.
-->

## Architecture

_(no entries yet)_

## Workflow

_(no entries yet)_

## Active Gotchas

_(no entries yet)_
MEOF
say "[ok] ensured Dreaming memory store at .assert-iq/memory/"

# ---- 1. render session-events wiring from template -----------------------
# Substitute __PACK_ROOT__ with this absolute pack path. VS Code Copilot
# does not propagate any env var that carries the workspace path to event
# commands, so the fallback path must be baked in at install time. Claude
# Code's CLAUDE_PLUGIN_ROOT still takes precedence at runtime.
render_events_template "$EVENTS_TEMPLATE" "$EVENTS_SRC" "$ROOT" \
  || fail "failed to render $EVENTS_SRC from template"
say "[ok] rendered .assert-iq/dreaming/session-events.json (pack root: $ROOT)"

# ---- 2. sync session-events into settings --------------------------------
# IMPORTANT: .claude/settings.json is NOT a copy of session-events.json. The two
# consumers use incompatible hook schemas:
#
#   VS Code Copilot : handlers sit directly in the event array and support
#                     osx/linux/windows command overrides.
#   Claude Code     : requires a matcher-group wrapper with a nested "hooks"
#                     array, has no platform keys, and picks the interpreter via
#                     a "shell" field.
#
# Copying the Copilot shape into .claude/settings.json yields a file Claude Code
# silently ignores -- exactly how Dreaming came to be dead under Claude Code
# while still working under VS Code on macOS. Render the Claude-shaped template.
# Enforced by unit-hook-schema.py.
render_events_template "$CLAUDE_HOOKS_TEMPLATE" "$CLAUDE_HOOKS_SRC" "$ROOT"   || fail "failed to render Claude hooks from $CLAUDE_HOOKS_TEMPLATE"

# Resolve a working Python 3 for the JSON merge. `python3` is not a reliable
# name (Windows ships a Store stub called python3 and python.org ships no
# python3.exe at all), so probe by EXECUTING each candidate. Same contract as
# .assert-iq/dreaming/scripts/lib/dream-utils.sh and the test lib.
AIQ_PY=""
for _cand in python3 python; do
    command -v "$_cand" >/dev/null 2>&1 || continue
    if "$_cand" -c 'import sys; sys.exit(0 if sys.version_info[0] == 3 else 1)' >/dev/null 2>&1; then
        AIQ_PY="$_cand"; break
    fi
done
if [[ -z "$AIQ_PY" ]] && command -v py >/dev/null 2>&1; then
    py -3 -c 'import sys; sys.exit(0)' >/dev/null 2>&1 && AIQ_PY="py -3"
fi

merge_hooks_key() {
    # Replace ONLY the .hooks key in $1 with the one from $2, preserving every
    # other key. Stage next to the destination so the final mv is atomic on the
    # same filesystem, and never overwrite on failure.
    #
    # Python first, jq second. This used to be jq-only, which made the installer
    # NON-IDEMPOTENT on any machine without jq: the first run copied the file,
    # and the second run hit "jq not installed and .claude/settings.json already
    # exists" and aborted -- on stock macOS, which ships Python 3 but not jq,
    # every re-run of the documented Path A failed.
    local dst="$1" src="$2" tmp
    tmp="$(mktemp "$dst.XXXXXX")" || return 1
    if [[ -n "$AIQ_PY" ]]; then
        if $AIQ_PY - "$dst" "$src" "$tmp" <<'PY'
import json, sys
dst, src, out = sys.argv[1], sys.argv[2], sys.argv[3]
with open(dst, encoding="utf-8") as f:
    existing = json.load(f)
with open(src, encoding="utf-8") as f:
    new = json.load(f)
if not isinstance(existing, dict):
    raise SystemExit("existing settings.json is not a JSON object")
existing["hooks"] = new.get("hooks")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    json.dump(existing, f, indent=2)
    f.write("\n")
PY
        then
            [[ -s "$tmp" ]] || { rm -f "$tmp"; return 1; }
            mv "$tmp" "$dst"
            MERGE_TOOL="python"
            return 0
        fi
        rm -f "$tmp"
        return 1
    fi
    if command -v jq >/dev/null 2>&1; then
        if jq -s '.[0] as $existing | .[1] as $new | $existing + {hooks: $new.hooks}' \
                "$dst" "$src" > "$tmp" && [[ -s "$tmp" ]]; then
            mv "$tmp" "$dst"
            MERGE_TOOL="jq"
            return 0
        fi
        rm -f "$tmp"
        return 1
    fi
    rm -f "$tmp"
    return 2   # no merge tool at all
}

if [[ -f "$SETTINGS_DST" ]]; then
    MERGE_TOOL=""
    # `|| merge_rc=$?` is required: this script runs under `set -e`, so calling
    # the function bare would abort the whole install on a non-zero return
    # before the case below could turn it into an actionable message.
    merge_rc=0
    merge_hooks_key "$SETTINGS_DST" "$CLAUDE_HOOKS_SRC" || merge_rc=$?
    case "$merge_rc" in
        0) say "[ok] merged hooks key -> .claude/settings.json (via $MERGE_TOOL; your other keys preserved)" ;;
        2) fail "no JSON tool available (need Python 3 or jq) and .claude/settings.json already exists; merge the 'hooks' key from $CLAUDE_HOOKS_SRC manually" ;;
        *) fail "merge failed; $SETTINGS_DST left untouched (source: $CLAUDE_HOOKS_SRC)" ;;
    esac
else
    cp "$CLAUDE_HOOKS_SRC" "$SETTINGS_DST"
    say "[ok] wrote .claude/settings.json (hooks key)"
fi

# ---- 3. wire skills ------------------------------------------------------
# One canonical skill tree (.github/skills), linked into each harness's
# expected location. This is why skills cannot drift across harnesses the way
# agents did at v2.0 -- there is only ever one copy.
skills_dest_disposable() {
    # 0 (disposable) if replacing directory $1 loses NOTHING: every file under
    # it also exists under $2 with identical bytes. An empty directory is
    # disposable by definition -- the loop body never runs.
    local dst="$1" src="$2" f rel
    [[ -d "$dst" ]] || return 1
    [[ -d "$src" ]] || return 1
    while IFS= read -r f; do
        [[ -n "$f" ]] || continue
        rel="${f#"$dst"/}"
        [[ -f "$src/$rel" ]] || return 1
        cmp -s "$f" "$src/$rel" || return 1
    done < <(find "$dst" -type f 2>/dev/null)
    return 0
}

link_skills() {
    # $1 = destination path, $2 = relative link target, $3 = label
    local dst="$1" src_rel="$2" label="$3"
    local src_abs="$ROOT/.github/skills"

    # This used to `rm -rf "$dst"` unconditionally. install.sh is documented as
    # "run after dropping the pack into a repo", so $ROOT can be the USER'S
    # repo -- and if they already kept their own skills in .kiro/skills or
    # .claude/skills, that deleted them outright. Silent data loss, and a
    # harsher version of the sidecar bug reported from the field.
    #
    # Only reclaim a destination that is ours (empty, or byte-identical to the
    # canonical tree). Where the user has their own skills, MERGE ours in
    # alongside and never delete.
    if [[ -d "$dst" ]] && ! [[ -L "$dst" ]] && ! skills_dest_disposable "$dst" "$src_abs"; then
        if [[ ! -d "$src_abs" ]]; then
            fail "missing $src_abs; cannot merge skills"
        fi
        cp -R "$src_abs/." "$dst/"
        say "[ok] merged .github/skills -> $label (your existing skills kept; re-run install.sh after skill changes)"
        return 0
    fi

    if [[ -L "$dst" || -e "$dst" ]]; then
        rm -rf "$dst"
    fi
    if ln -s "$src_rel" "$dst" 2>/dev/null; then
        say "[ok] linked $label -> $src_rel"
        return 0
    fi
    if [[ -d "$ROOT/.github/skills" ]]; then
        cp -R "$ROOT/.github/skills" "$dst"
        say "[ok] copied .github/skills -> $label (symlink unavailable; re-run install.sh after skill changes)"
        return 0
    fi
    fail "missing $ROOT/.github/skills; cannot link or copy skills"
}

link_skills "$SKILLS_DST" "$SKILLS_SRC_REL" ".claude/skills"

# ---- 4. wire Kiro --------------------------------------------------------
# Kiro reads none of .github/* or .claude/*, so it needs its own wiring. Its
# steering and agents are committed pack source (generated by
# scripts/sync-kiro.sh at authoring time, not at install time), so the only
# install-time work is the hook file and the skills link.
if [[ -f "$KIRO_HOOKS_TEMPLATE" ]]; then
    mkdir -p "$ROOT/.kiro/hooks"
    # Same __PACK_ROOT__ substitution as the other two harnesses. Kiro also
    # offers ${WORKSPACE_ROOT} at runtime, which the template prefers; the
    # baked path is the fallback for a pack installed outside the workspace.
    render_events_template "$KIRO_HOOKS_TEMPLATE" "$KIRO_HOOKS_DST" "$ROOT" \
      || fail "failed to render $KIRO_HOOKS_DST from $KIRO_HOOKS_TEMPLATE"
    say "[ok] rendered .kiro/hooks/assert-iq-dreaming.json (pack root: $ROOT)"
else
    say "[skip] $KIRO_HOOKS_TEMPLATE missing; Kiro Dreaming hooks not wired"
fi

mkdir -p "$ROOT/.kiro"
link_skills "$KIRO_SKILLS_DST" "$SKILLS_SRC_REL" ".kiro/skills"

say ""
say "Pack installed."
say "  Copilot reads .github/copilot-instructions.md, .github/instructions/*, .github/agents/*, .github/skills/*"
say "  Claude  reads CLAUDE.md, .claude/agents/*, .claude/skills/*, .claude/settings.json (session events)"
say "  Kiro    reads .kiro/steering/*, .kiro/agents/*, .kiro/skills/*, .kiro/hooks/*, .kiro/settings/mcp.json"
say "  Dreaming memory store: .assert-iq/memory/ (run /dream to consolidate)"
say ""
say "  Kiro note: hooks do not run in an untrusted workspace. If Dreaming is"
say "  not recording, trust the folder first."
