# install.ps1 -- wire the Assert.IQ agent pack into a repo for dual-target use.
# Idempotent: safe to re-run.
#
# What it does:
#   1. Renders .assert-iq\dreaming\session-events.json from its template with
#      the pack root baked in (VS Code Copilot has no env equivalent of
#      CLAUDE_PLUGIN_ROOT, so the absolute path must be substituted at
#      install time).
#   2. Syncs the rendered file -> .claude\settings.json (hooks key -- the
#      harness contract), preserving any other keys you already have there.
#      Written via staged temp file + Move-Item so an interrupt mid-write
#      cannot truncate your existing settings.
#   3. Scaffolds the Dreaming memory store at .assert-iq\memory\.
#   4. Creates .claude\skills as a symlink to ..\.github\skills so Claude
#      Code discovers the same skills Copilot does. Falls back to copy when
#      symlink creation requires Developer Mode and that mode is off.
#   5. Wires Kiro: renders .kiro\hooks\assert-iq-dreaming.json from the
#      Windows template and links .kiro\skills the same way as .claude\skills.
#      Kiro's steering and agents are committed pack source (generated by
#      scripts\sync-kiro.ps1 at authoring time), so they need no install step.
#
# Copilot needs no extra wiring -- it reads .github\* natively.
#
# Uninstall: pass -Uninstall to reverse the above. Other keys in
# .claude\settings.json and your .assert-iq\memory\ store are preserved.

[CmdletBinding()]
param(
    [switch]$Uninstall,
    # No-op; accepted for parity with bootstrap.ps1 (no prompts here).
    [switch]$Yes
)

$ErrorActionPreference = 'Stop'

# UTF-8 WITHOUT BOM, ON EVERY HOST.
#
# `Set-Content -Encoding UTF8` writes a byte-order mark on Windows PowerShell
# 5.1; PowerShell 7's UTF8 means UTF-8 *without* BOM. The pack's Python tooling
# reads JSON with encoding="utf-8", which REJECTS a BOM
# (json.JSONDecodeError: Expecting value: line 1 column 1), so on a stock
# Windows box every JSON file written here -- dream state, verdicts, the install
# manifest, .claude/settings.json -- became unparseable to calibration.py,
# memory-sanity.py, the verdict recorder and dreaming_service.py. The
# `-Encoding utf8NoBOM` value that would fix this exists only in PowerShell 6+,
# so write through .NET instead. Semantics match Set-Content: an array is joined
# with newlines and a trailing newline is added unless -NoNewline is given.
$script:AiqUtf8NoBom = New-Object System.Text.UTF8Encoding($false)
function Write-AiqUtf8 {
    param(
        [Parameter(Mandatory)][string] $Path,
        [Parameter()][AllowEmptyString()][AllowNull()] $Value,
        [switch] $NoNewline,
        [switch] $Append
    )
    if ($null -eq $Value) { $Value = @() }
    # Order matters. A [string] is itself IEnumerable (of chars), so it must be
    # tested FIRST. And the collection test must be IEnumerable, not
    # [System.Array]: several callers pass a
    # System.Collections.Generic.List[string], which is NOT an array. Getting
    # that wrong sent a List down the [string] cast, which joins with $OFS -- a
    # SPACE -- collapsing .git/info/exclude into a single line so git matched
    # nothing and trial mode silently stopped hiding anything.
    if ($Value -is [string]) {
        $text = $Value
    } elseif ($Value -is [System.Collections.IEnumerable]) {
        $text = (@($Value) | ForEach-Object { [string]$_ }) -join [Environment]::NewLine
    } else {
        $text = [string]$Value
    }
    if (-not $NoNewline -and $text.Length -ge 0) { $text += [Environment]::NewLine }
    if ($Append) {
        [System.IO.File]::AppendAllText($Path, $text, $script:AiqUtf8NoBom)
    } else {
        [System.IO.File]::WriteAllText($Path, $text, $script:AiqUtf8NoBom)
    }
}

$root         = Split-Path -Parent $PSCommandPath
$eventsTpl    = Join-Path $root '.assert-iq\dreaming\session-events.template.json'
$eventsSrc    = Join-Path $root '.assert-iq\dreaming\session-events.json'
# Claude Code needs a DIFFERENT hook shape than VS Code Copilot; see the
# comment at the sync step below. Rendered from its own template.
$claudeHooksTpl = Join-Path $root '.assert-iq\dreaming\claude-hooks.windows.template.json'
$claudeHooksSrc = Join-Path $root '.assert-iq\dreaming\.claude-hooks.rendered.json'
$memoryDir    = Join-Path $root '.assert-iq\memory'
$hooksSrcLegacy = Join-Path $root 'hooks\hooks.json'
$settingsDst  = Join-Path $root '.claude\settings.json'
$skillsDst    = Join-Path $root '.claude\skills'
$skillsSrcRel = '..\.github\skills'
$skillsSrcAbs = Join-Path $root '.github\skills'
$renderLib    = Join-Path $root '.assert-iq\dreaming\scripts\lib\render-events.ps1'

# Kiro (third harness). Unlike Claude, Kiro's hooks are a STANDALONE file in
# .kiro\hooks\ rather than a key inside a shared settings file, so there is no
# merge step and no risk of clobbering unrelated user config -- the file is
# ours outright. Skills use the same symlink trick as .claude\skills.
#
# The WINDOWS template is the right one here: Kiro spawns hook commands with
# shell:true, which is cmd.exe on Windows, and the command inside shells out to
# powershell. The posix template's /bin/sh syntax would not run.
$kiroHooksTpl = Join-Path $root '.assert-iq\dreaming\kiro-hooks.windows.template.json'
$kiroHooksDst = Join-Path $root '.kiro\hooks\assert-iq-dreaming.json'
$kiroSkillsDst = Join-Path $root '.kiro\skills'

function Say($msg) { Write-Host $msg }
function Fail($msg) { throw "install.ps1: $msg" }

function Test-SkillsDestDisposable {
    # $true if replacing directory -Dst loses NOTHING: every file under it also
    # exists under -Src with identical content. An empty directory is
    # disposable by definition. Mirrors the helper in scripts\bootstrap.ps1.
    param(
        [Parameter(Mandatory)][string]$Dst,
        [Parameter(Mandatory)][string]$Src
    )
    if (-not (Test-Path -LiteralPath $Dst -PathType Container)) { return $false }
    if (-not (Test-Path -LiteralPath $Src -PathType Container)) { return $false }
    $dstFull = (Resolve-Path -LiteralPath $Dst).Path
    foreach ($f in (Get-ChildItem -LiteralPath $Dst -Recurse -File -Force -ErrorAction SilentlyContinue)) {
        $rel = $f.FullName.Substring($dstFull.Length).TrimStart([char]92)
        $peer = Join-Path $Src $rel
        if (-not (Test-Path -LiteralPath $peer -PathType Leaf)) { return $false }
        if ((Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash -ne
            (Get-FileHash -LiteralPath $peer      -Algorithm SHA256).Hash) { return $false }
    }
    return $true
}

function Remove-SkillsPath {
    # PS 5.1 will follow a directory symlink/junction with -Recurse and delete
    # the REAL .github\skills source. Detect the link and unlink instead.
    # Shared by the uninstall path and the re-link step so the dangerous case
    # is handled identically in both.
    param([Parameter(Mandatory)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return }
    $item = Get-Item -LiteralPath $Path -Force
    if ($item.LinkType -in @('SymbolicLink','Junction')) {
        try { [System.IO.Directory]::Delete($Path) }
        catch { Remove-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue }
    } else {
        Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction SilentlyContinue
    }
}

# Defense-in-depth: refuse to operate if $root is empty or a filesystem root.
if ([string]::IsNullOrWhiteSpace($root) -or
    $root -match '^[A-Za-z]:\\?$' -or
    $root -eq '\' -or $root -eq '/') {
    Fail "refusing to operate at filesystem root (root='$root')"
}

# ---- Uninstall path ------------------------------------------------------
if ($Uninstall) {
    Say '=== Assert.IQ install.ps1: uninstall ==='
    if (Test-Path -LiteralPath $skillsDst) {
        Remove-SkillsPath -Path $skillsDst
        Say "[ok] removed $skillsDst"
    }
    if (Test-Path -LiteralPath $kiroSkillsDst) {
        Remove-SkillsPath -Path $kiroSkillsDst
        Say "[ok] removed $kiroSkillsDst"
    }
    if (Test-Path -LiteralPath $settingsDst -PathType Leaf) {
        try {
            $existing = Get-Content -LiteralPath $settingsDst -Raw | ConvertFrom-Json
            $out = [ordered]@{}
            foreach ($prop in $existing.PSObject.Properties) {
                if ($prop.Name -ne 'hooks') { $out[$prop.Name] = $prop.Value }
            }
            if ($out.Keys.Count -eq 0) {
                Remove-Item -LiteralPath $settingsDst -Force
                Say "[ok] removed $settingsDst (was hooks-only)"
            } else {
                $tmp = "$settingsDst.$([guid]::NewGuid().ToString('N')).tmp"
                Write-AiqUtf8 -Path $tmp -Value ([pscustomobject]$out | ConvertTo-Json -Depth 32)
                Move-Item -LiteralPath $tmp -Destination $settingsDst -Force
                Say "[ok] stripped hooks key from $settingsDst"
            }
        } catch {
            Say "[skip] could not parse ${settingsDst}: $_  (left untouched)"
        }
    }
    if (Test-Path -LiteralPath $eventsSrc -PathType Leaf) {
        Remove-Item -LiteralPath $eventsSrc -Force -ErrorAction SilentlyContinue
        Say "[ok] removed $eventsSrc"
    }
    if (Test-Path -LiteralPath $claudeHooksSrc -PathType Leaf) {
        Remove-Item -LiteralPath $claudeHooksSrc -Force -ErrorAction SilentlyContinue
        Say "[ok] removed $claudeHooksSrc"
    }
    if (Test-Path -LiteralPath $hooksSrcLegacy -PathType Leaf) {
        Remove-Item -LiteralPath $hooksSrcLegacy -Force -ErrorAction SilentlyContinue
        Say "[ok] removed legacy $hooksSrcLegacy"
    }
    # Kiro-generated wiring. Steering, agents and settings\mcp.json are
    # committed pack SOURCE, not install output, so they stay -- same reason
    # .github\ stays.
    if (Test-Path -LiteralPath $kiroHooksDst -PathType Leaf) {
        Remove-Item -LiteralPath $kiroHooksDst -Force -ErrorAction SilentlyContinue
        Say "[ok] removed $kiroHooksDst"
    }
    $kiroHooksDir = Join-Path $root '.kiro\hooks'
    if ((Test-Path -LiteralPath $kiroHooksDir) -and `
        -not (Get-ChildItem -LiteralPath $kiroHooksDir -Force -ErrorAction SilentlyContinue)) {
        Remove-Item -LiteralPath $kiroHooksDir -Force -ErrorAction SilentlyContinue
        Say "[ok] removed empty .kiro\hooks\"
    }

    $claudeDir = Join-Path $root '.claude'
    if ((Test-Path -LiteralPath $claudeDir) -and `
        -not (Get-ChildItem -LiteralPath $claudeDir -Force -ErrorAction SilentlyContinue)) {
        Remove-Item -LiteralPath $claudeDir -Force -ErrorAction SilentlyContinue
        Say "[ok] removed empty .claude\"
    }
    Say ''
    Say 'Uninstall complete.'
    Say 'Pack source files (.github\, .kiro\steering, .kiro\agents, CLAUDE.md,'
    Say 'AGENTS.md, etc.) are unchanged.'
    Say 'Your .assert-iq\memory\ store is preserved.'
    return
}

if (-not (Test-Path -LiteralPath $eventsTpl)) { Fail "missing $eventsTpl" }
if (-not (Test-Path -LiteralPath $renderLib)) { Fail "missing $renderLib" }

. $renderLib

New-Item -ItemType Directory -Force -Path (Join-Path $root '.claude\agents') | Out-Null

# ---- 0. scaffold the Dreaming memory store -------------------------------
New-Item -ItemType Directory -Force -Path (Join-Path $memoryDir 'topics') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $memoryDir 'logs') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $memoryDir '.dream') | Out-Null

# Verdict archive (v1.7.0+) and pre-dream memory snapshots. Both are
# git-ignored runtime sinks, so a fresh clone has neither; without them the
# first /risk-assess-pr or /dream has nowhere to write.
New-Item -ItemType Directory -Force -Path (Join-Path $root '.assert-iq\verdicts\archive') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $root '.assert-iq\dreaming\.snapshots') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $root '.assert-iq\business-metrics\reports') | Out-Null
$statePath = Join-Path $memoryDir '.dream\state.json'
if (-not (Test-Path -LiteralPath $statePath)) {
    Write-AiqUtf8 -Path $statePath -Value "{`n  `"last_dream_utc`": null,`n  `"sessions_since_dream`": 0`n}"
}
# MEMORY.md is git-ignored (never ship maintainer memory); seed a clean index
# if this clone doesn't have one yet.
$memoryIndex = Join-Path $memoryDir 'MEMORY.md'
if (-not (Test-Path -LiteralPath $memoryIndex)) {
    $seed = @'
# MEMORY.md -- Project Memory Index

_Last consolidated: never -- run `/dream` to populate_

<!--
Long-term memory INDEX for the Assert.IQ Dreaming feature (loaded at session
start, index only). Maintained by the /dream consolidation pass:
  - Hard cap: 200 lines; one-line pointers into topics/.
  - Absolute dates only. Facts/decisions/preferences, not transcript excerpts.
Hand-edit freely; the instruction files under .github/instructions/ are the
immutable rules tier and are never modified by dreaming.
-->

## Architecture

_(no entries yet)_

## Workflow

_(no entries yet)_

## Active Gotchas

_(no entries yet)_
'@
    Write-AiqUtf8 -Path $memoryIndex -Value $seed
}
Say "[ok] ensured Dreaming memory store at .assert-iq\memory\"

# ---- 1. render session-events wiring from template -----------------------
Render-EventsTemplate -Template $eventsTpl -Out $eventsSrc -PackRoot $root
Say "[ok] rendered .assert-iq\dreaming\session-events.json (pack root: $root)"

# ---- 1. sync hooks block -------------------------------------------------
# IMPORTANT: .claude\settings.json is NOT a copy of session-events.json. The two
# consumers use incompatible hook schemas:
#
#   VS Code Copilot : handlers sit directly in the event array and support
#                     osx/linux/windows command overrides.
#   Claude Code     : requires a matcher-group wrapper with a nested "hooks"
#                     array, has no platform keys, and picks the interpreter via
#                     a "shell" field.
#
# Copying the Copilot shape into .claude\settings.json yields a file Claude Code
# silently ignores -- exactly how Dreaming came to be dead under Claude Code
# while still working under VS Code on macOS. Render the Claude-shaped template
# (Windows variant: powershell handlers, so the bash/python3 path is never used
# on Windows). Enforced by unit-hook-schema.py.
if (-not (Test-Path -LiteralPath $claudeHooksTpl)) { Fail "missing $claudeHooksTpl" }
Render-EventsTemplate -Template $claudeHooksTpl -Out $claudeHooksSrc -PackRoot $root

# Stage the merged JSON to a sibling temp file, validate non-empty, then
# atomically Move-Item into place. Prevents truncation of the user's
# existing .claude\settings.json on interrupt or partial-write.
$newHooksRaw = Get-Content -LiteralPath $claudeHooksSrc -Raw
try {
    $newHooks = $newHooksRaw | ConvertFrom-Json
} catch {
    Fail "rendered $hooksSrc is not valid JSON: $($_.Exception.Message)"
}

if (Test-Path -LiteralPath $settingsDst) {
    $existingRaw = Get-Content -LiteralPath $settingsDst -Raw
    try {
        $existing = $existingRaw | ConvertFrom-Json
    } catch {
        Fail "existing $settingsDst is not valid JSON; left untouched"
    }
    if ($null -eq $existing) { $existing = [pscustomobject]@{} }
    $existing | Add-Member -NotePropertyName hooks -NotePropertyValue $newHooks.hooks -Force
    $merged = $existing | ConvertTo-Json -Depth 50
} else {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $settingsDst) | Out-Null
    $merged = $newHooks | ConvertTo-Json -Depth 50
}

if ([string]::IsNullOrWhiteSpace($merged)) {
    Fail "refusing to write empty settings.json"
}

$settingsTmp = "$settingsDst.$([guid]::NewGuid().ToString('N')).tmp"
try {
    Write-AiqUtf8 -Path $settingsTmp -Value $merged
    if (-not (Test-Path -LiteralPath $settingsTmp) -or
        (Get-Item -LiteralPath $settingsTmp).Length -eq 0) {
        Fail "staged settings file is empty: $settingsTmp"
    }
    Move-Item -LiteralPath $settingsTmp -Destination $settingsDst -Force
    $settingsTmp = $null
} finally {
    if ($settingsTmp -and (Test-Path -LiteralPath $settingsTmp)) {
        Remove-Item -LiteralPath $settingsTmp -Force -ErrorAction SilentlyContinue
    }
}
Say "[ok] synced hooks -> .claude\settings.json"

# ---- 2. wire skills ------------------------------------------------------
# One canonical skill tree (.github\skills), linked into each harness's
# expected location. This is why skills cannot drift across harnesses the way
# agents did at v2.0 -- there is only ever one copy.
if (-not (Test-Path -LiteralPath $skillsSrcAbs)) {
    Fail "missing skills source: $skillsSrcAbs"
}

function Link-Skills {
    param(
        [Parameter(Mandatory)][string]$Dst,
        [Parameter(Mandatory)][string]$SrcRel,
        [Parameter(Mandatory)][string]$Label
    )
    # Remove-SkillsPath used to run unconditionally. install.ps1 is documented
    # as "run after dropping the pack into a repo", so $root can be the USER'S
    # repo -- and if they already kept their own skills in .kiro\skills or
    # .claude\skills, that deleted them outright. Silent data loss, and a
    # harsher version of the sidecar bug reported from the field.
    #
    # Only reclaim a destination that is ours (empty, or byte-identical to the
    # canonical tree). Where the user has their own skills, MERGE ours in
    # alongside and never delete.
    if ((Test-Path -LiteralPath $Dst -PathType Container) -and
        ((Get-Item -LiteralPath $Dst -Force).LinkType -notin @('SymbolicLink','Junction')) -and
        (-not (Test-SkillsDestDisposable -Dst $Dst -Src $skillsSrcAbs))) {
        Copy-Item -Path (Join-Path $skillsSrcAbs '*') -Destination $Dst -Recurse -Force
        Say "[ok] merged .github\skills -> $Label (your existing skills kept; re-run install.ps1 after skill changes)"
        return
    }

    Remove-SkillsPath -Path $Dst
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Dst) | Out-Null
    try {
        # Create the link from INSIDE its parent directory. NTFS stores a
        # relative symlink target verbatim and resolves it against the link's
        # own directory, but Windows PowerShell 5.1 first validates -Target
        # against the CURRENT working directory. Run install.ps1 from anywhere
        # other than the pack root and 5.1 rejected '..\.github\skills'
        # ("Cannot find path 'C:\Users\<you>\.github\skills'"), silently
        # degrading the link to a COPY even with Developer Mode enabled.
        # Pushing to the parent makes the validation agree with the filesystem
        # while keeping the stored target relative -- which matters, because
        # bootstrap.ps1 recognises a pack-owned link by comparing that exact
        # relative string.
        Push-Location -LiteralPath (Split-Path -Parent $Dst)
        try {
            New-Item -ItemType SymbolicLink -Path $Dst -Target $SrcRel -ErrorAction Stop | Out-Null
        } finally {
            Pop-Location
        }
        Say "[ok] linked $Label -> $SrcRel"
    } catch {
        # Symlink creation on Windows requires Developer Mode or admin rights.
        # Fall back to a recursive copy so the install still succeeds.
        Copy-Item -Recurse -Force -LiteralPath $skillsSrcAbs -Destination $Dst
        Say "[ok] copied .github\skills -> $Label (symlink unsupported: $($_.Exception.Message); re-run install.ps1 after skill changes)"
    }
}

Link-Skills -Dst $skillsDst -SrcRel $skillsSrcRel -Label '.claude\skills'

# ---- 3. wire Kiro --------------------------------------------------------
# Kiro reads none of .github\* or .claude\*, so it needs its own wiring. Its
# steering and agents are committed pack source (generated by
# scripts\sync-kiro.ps1 at authoring time, not at install time), so the only
# install-time work is the hook file and the skills link.
if (Test-Path -LiteralPath $kiroHooksTpl) {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $kiroHooksDst) | Out-Null
    # Same __PACK_ROOT__ substitution as the other two harnesses -- and
    # Render-EventsTemplate JSON-escapes the backslashes, which matters here
    # because a raw Windows path inside a JSON string would produce invalid
    # escape sequences (\U, \d) and Kiro would reject the whole hook file.
    # Kiro also offers ${WORKSPACE_ROOT} at runtime, which the template
    # prefers; the baked path is the fallback for a pack installed outside the
    # workspace.
    Render-EventsTemplate -Template $kiroHooksTpl -Out $kiroHooksDst -PackRoot $root
    Say "[ok] rendered .kiro\hooks\assert-iq-dreaming.json (pack root: $root)"
} else {
    Say "[skip] $kiroHooksTpl missing; Kiro Dreaming hooks not wired"
}

Link-Skills -Dst $kiroSkillsDst -SrcRel $skillsSrcRel -Label '.kiro\skills'

Say ""
Say "Pack installed."
Say "  Copilot reads .github\copilot-instructions.md, .github\instructions\*, .github\agents\*, .github\skills\*"
Say "  Claude  reads CLAUDE.md, .claude\agents\*, .claude\skills\*, .claude\settings.json (session events)"
Say "  Kiro    reads .kiro\steering\*, .kiro\agents\*, .kiro\skills\*, .kiro\hooks\*, .kiro\settings\mcp.json"
Say "  Dreaming memory store: .assert-iq\memory\ (run /dream to consolidate)"
Say ""
Say "  Kiro note: hooks do not run in an untrusted workspace. If Dreaming is"
Say "  not recording, trust the folder first."
