#!/usr/bin/env python3
r"""
UNIT: installed-payload commands must resolve in an installed workspace.

WHY THIS EXISTS

`scripts/` is pack-only. bootstrap.sh copies exactly four trees --
`.assert-iq`, `.github/skills`, `.github/agents`, `.claude/agents` -- plus a
handful of root files. It has never copied the top-level `scripts/` directory,
and it should not: those are installer and pack-maintenance tools, not consumer
artifacts. `.assert-iq/.install-manifest.json` in a real install lists ~146
paths and `scripts/` is correctly absent from every one of them.

The trap is that the FILES WE DO INSTALL kept telling agents to run those
scripts by a bare relative path. In the pack checkout `bash
scripts/check-environment.sh` resolves and everyone's manual testing passed. In
an installed workspace the same line cannot resolve, and an agent that hits it
does not conclude "this command is pack-only" -- it concludes THE INSTALL IS
BROKEN. Two shipped instances of this:

  * assert-iq-tailor Phase 0 step 3b ran `bash scripts/check-environment.sh`.
    Running /assert-iq-tailor in a normal installed workspace produced:
    "this install has no top-level scripts/ directory ... Worth checking whether
    this install predates those scripts or they weren't copied." Both guesses
    were wrong. The install was perfect. The skill was not.

  * assert-iq-bootstrap gave `scripts/bootstrap.sh --graduate` and the four
    `--uninstall` forms as bare paths. Graduating is the one command a trial
    installer is GUARANTEED to need, and it was unreachable from the workspace
    it was meant to act on.

Nothing caught either. validate-documentation-integrity.sh is content-presence
checks; no test asserted that a command inside the payload resolves after
install. This is that test.

WHAT COUNTS AS A VIOLATION

Command-shaped invocations only -- a verb (`bash`/`sh`/`pwsh`/`powershell`)
directly followed by an unresolved `scripts/...` path, or a fenced code line
that starts with one. Prose references are fine and often necessary: the fix for
the two bugs above was to EXPLAIN that `scripts/` is pack-only, which requires
naming it. `` `scripts/sync-agents.sh` `` in a sentence is documentation;
`bash scripts/sync-agents.sh` on its own line is an instruction that breaks.

The resolved forms pass because the character before `scripts` is `/` or `\`,
not whitespace:

    bash "${CLAUDE_PLUGIN_ROOT:-.}/scripts/check-environment.sh"     OK
    pwsh -File "$env:CLAUDE_PLUGIN_ROOT\scripts\bootstrap.ps1"       OK
    bash "$P/scripts/bootstrap.sh" --uninstall                       OK
    bash scripts/bootstrap.sh --graduate                             VIOLATION

SCOPE: instruction-bearing payload files (skills, agents, instruction files,
CLAUDE.md / AGENTS.md / copilot-instructions.md). Shell tests under
`.assert-iq/tests/` are deliberately excluded -- see KNOWN_UNFIXED.

PORTABILITY: stdlib only. Forces UTF-8 stdout because a Windows console
defaults to cp1252 and would raise UnicodeEncodeError on the arrows below.
Run from the repo root.
"""

import os
import re
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Trees and files bootstrap.sh actually installs (see copy_tree calls around
# bootstrap.sh:1913-2156) AND that carry instructions an agent will act on.
PAYLOAD_TREES = [
    ".github/skills",
    ".github/agents",
    ".github/instructions",
    ".claude/agents",
    # Kiro (third harness). process_kiro / Step-Kiro copy these three trees
    # into the workspace, so everything in them is payload an agent will read
    # and act on -- exactly like .claude/agents. Adding a harness without
    # widening this list would have let the whole defect class back in through
    # the new surface, which is how the original two bugs shipped.
    ".kiro/steering",
    ".kiro/agents",
    ".kiro/settings",
]
PAYLOAD_FILES = [
    "CLAUDE.md",
    "AGENTS.md",
    ".github/copilot-instructions.md",
]

VERB = r"(?:bash|sh|pwsh|powershell)"
# A command verb, optional flags, then `scripts/` with only whitespace between.
CMD_FORM = re.compile(
    r"(?:^|[|(&;`]|\s)" + VERB + r"\s+(?:-NoProfile\s+)?(?:-File\s+)?"
    r"(scripts[/\\][A-Za-z0-9._-]+)"
)
# A fenced-code line that IS the invocation, e.g. `scripts/bootstrap.sh --graduate`
BARE_LINE = re.compile(r"^\s*(scripts[/\\][A-Za-z0-9._-]+)")

FENCE = re.compile(r"^\s*```")

# Declared, deliberate exceptions. Anything NOT listed here fails. Never widen
# the regexes to silence a finding -- add it here with a reason, or fix it.
ACCEPTED = {
    # These 8 are GENERATED by scripts/sync-agents.sh, which stamps a provenance
    # header telling a maintainer how to regenerate them. The line is addressed
    # to whoever is editing the pack, not to an agent running in a consumer
    # workspace, and it sits in a comment block that is never executed. Fixing
    # it means changing the generator's header template; tracked separately.
    ".github/agents/specialists/calibration-specialist.agent.md",
    ".github/agents/specialists/coverage-analyst.agent.md",
    ".github/agents/specialists/flake-adjudicator.agent.md",
    ".github/agents/specialists/hotspot-analyzer.agent.md",
    ".github/agents/specialists/memory-curator.agent.md",
    ".github/agents/specialists/oracle-grader.agent.md",
    ".github/agents/specialists/risk-scorer.agent.md",
    ".github/agents/specialists/traceability-auditor.agent.md",
}

# Known, UNFIXED instances of this same defect class that are out of this test's
# scope. Listed so they are not forgotten -- reported as a warning, not a pass.
#
# e2e-agent-parity.sh used to live here: its P5/P6 hard-failed whenever
# scripts/sync-agents.{sh,ps1} were absent, which was every installed workspace,
# so a consumer running run-all.sh got two failures blaming a "missing"
# sync-agents.sh. Fixed twice over: P5/P6 now SKIP off-pack (exit 2, which
# run-all.sh reports as NOT APPLICABLE rather than IN PARITY), and
# process_assert_iq in bootstrap.sh no longer ships tests/_qi/automated/ at all
# -- it validated the pack, not the user's code, and sat one directory from the
# tests/_qi/manual/ and tests/_qi/exploratory/ trees where the user's GENERATED
# QI tests live. That exclusion is why this test does not scan tests/_qi/
# automated/: it is no longer payload. tests/_qi/regression/ still ships,
# because golden-corpus.jsonl is a consumer runtime artifact.
KNOWN_UNFIXED = []


def iter_payload():
    for path in PAYLOAD_FILES:
        if os.path.isfile(path):
            yield path
    for tree in PAYLOAD_TREES:
        for root, _dirs, names in os.walk(tree):
            for n in sorted(names):
                if n.endswith((".md", ".sh", ".ps1")):
                    yield os.path.join(root, n).replace("\\", "/")


def scan(path):
    """Return [(lineno, matched_path, line)] of unresolved invocations."""
    hits = []
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        lines = fh.read().splitlines()

    in_fence = False
    for i, line in enumerate(lines, 1):
        if FENCE.match(line):
            in_fence = not in_fence
            continue

        m = CMD_FORM.search(line)
        if m:
            hits.append((i, m.group(1), line.strip()))
            continue

        # A bare `scripts/...` as the command itself only reads as an
        # invocation inside a code fence; in prose it is a reference.
        if in_fence:
            m = BARE_LINE.match(line)
            if m:
                hits.append((i, m.group(1), line.strip()))
    return hits


def check_payload_composition():
    """
    The pack's own suite must stay OUT of the payload, and the two installer
    implementations must agree about it.

    tests/_qi/automated/ validates the pack; tests/_qi/regression/ holds
    golden-corpus.jsonl, which is a CONSUMER runtime artifact that
    config.yaml > calibration.golden_corpus_path points at. Excluding the wrong
    one of those two breaks the post-dream regression gate; excluding neither
    puts 28 pack tests one directory from the user's own tests/_qi/manual/ and
    tests/_qi/exploratory/ trees, where 9 of them fail on missing pack-only
    files and make a healthy install look broken.

    bash and PowerShell carry separate exclude lists, so they can drift the way
    the sync-agents tool map could before check P6 existed. Compare them.
    """
    problems = []

    sh_path, ps_path = "scripts/bootstrap.sh", "scripts/bootstrap.ps1"
    if not (os.path.isfile(sh_path) and os.path.isfile(ps_path)):
        # Off-pack: scripts/ is pack-only, so there is nothing to compare.
        return [], True

    sh = open(sh_path, encoding="utf-8", errors="replace").read()
    ps = open(ps_path, encoding="utf-8", errors="replace").read()

    m_sh = re.search(r'local\s+_ex="([^"]*)"', sh)
    m_ps = re.search(r"\$aiqExclude\s*=\s*@\(([^)]*)\)", ps)
    if not m_sh:
        return ["could not find the _ex exclude list in scripts/bootstrap.sh"], False
    if not m_ps:
        return ["could not find $aiqExclude in scripts/bootstrap.ps1"], False

    sh_ex = set(m_sh.group(1).split())
    ps_ex = set(re.findall(r"'([^']*)'", m_ps.group(1)))

    if sh_ex != ps_ex:
        problems.append(
            "bootstrap.sh and bootstrap.ps1 exclude lists DIVERGE -- "
            f"only in .sh: {sorted(sh_ex - ps_ex) or '(none)'}; "
            f"only in .ps1: {sorted(ps_ex - sh_ex) or '(none)'}"
        )

    for name, lst in (("bootstrap.sh", sh_ex), ("bootstrap.ps1", ps_ex)):
        if "tests/_qi/automated/" not in lst:
            problems.append(
                f"{name} no longer excludes tests/_qi/automated/ -- the pack's "
                "own suite would ship into consumer workspaces again"
            )
        if any(e.startswith("tests/_qi/regression") for e in lst):
            problems.append(
                f"{name} excludes tests/_qi/regression/ -- golden-corpus.jsonl "
                "is a consumer runtime artifact and MUST still be installed"
            )
    return problems, False


def main():
    if not os.path.isdir(".github/skills"):
        print("✗ run this from the repo root (.github/skills not found)")
        return 1

    violations = []
    accepted_hits = 0
    scanned = 0

    for path in iter_payload():
        scanned += 1
        hits = scan(path)
        if not hits:
            continue
        if path in ACCEPTED:
            accepted_hits += len(hits)
            continue
        violations.append((path, hits))

    print("=== Installed-payload path resolvability ===")
    print("")
    print(f"scanned {scanned} payload files; "
          f"{len(ACCEPTED)} accepted exceptions ({accepted_hits} lines)")
    print("")

    if violations:
        print("✗ FAIL — payload files invoke pack-only scripts/ by a path that")
        print("  cannot resolve in an installed workspace:")
        print("")
        for path, hits in violations:
            for lineno, target, text in hits:
                print(f"  {path}:{lineno}")
                print(f"      {text}")
                print(f"      → {target} is not installed; resolve via "
                      f"$CLAUDE_PLUGIN_ROOT or state that it is pack-only")
                print("")
        print("  `scripts/` is pack-only BY DESIGN. Either route the command")
        print("  through the pack root, or say plainly that it does not run")
        print("  here — never let an agent infer the install is broken.")

    if KNOWN_UNFIXED:
        print("")
        print("⚠ known unfixed (out of scope for this test, tracked here):")
        for path, why in KNOWN_UNFIXED:
            print(f"    {path}")
            print(f"      {why}")

    comp_problems, comp_skipped = check_payload_composition()
    print("")
    print("--- payload composition (pack suite must stay out) ---")
    if comp_skipped:
        print("  ⏭️  SKIP — no scripts/ tree, so this is not the pack checkout")
    elif comp_problems:
        for p in comp_problems:
            print(f"  ✗ {p}")
    else:
        print("  ✓ tests/_qi/automated/ excluded by both installers; "
              "tests/_qi/regression/ still ships")

    if violations or comp_problems:
        return 1

    print("")
    print("✓ PASS — every scripts/ invocation in the payload resolves or is")
    print("  declared pack-only, and the pack suite stays out of the payload")
    return 0


if __name__ == "__main__":
    sys.exit(main())
